### PR TITLE
avoid root "/" matches every passed in path on checking partialMatch

### PR DESCRIPTION
**Pull request by jamuhl**
using router5 having routes setup like:

```
router
  .addNode('home', '/?:lng')
  .addNode('page1', '/page1?:lng');
```

the home route will always match in RouteNode: https://github.com/troch/route-node/blob/master/modules/RouteNode.js#L147

as any url will match `^\/`

### CODE REVIEW

**Comment by troch** [comment]
As you said, any URL will match `/`, it is not an issue with path-parser, it is an issue with route-node and marshalling the children of a node in the right order.

I have a test case for this: https://github.com/troch/route-node/blob/master/test/main.js#L254-L267, adding query parameters to each route make it fail, I'll release a new version promptly of route-node. I am closing this for now, thanks for bringing my attention to it.

I have no contributing guidelines on this repo, but I should link to https://github.com/router5/router5/blob/master/CONTRIBUTING.md (regarding commit messages).

Finally, with 2.0.0 around the corner (a week or so), I'll introduce (maybe not right at release time) permanent query parameters: you define them with your router and their last known value will survive route changes (unless overwritten), which I think is what you are trying to do with `?:lng`.

**Comment by jamuhl** [comment]
not sure...

path: `/any/strange/long/route` will partialMatch `new Path('/')` which is not expected behaviour i think (at least for me)

but anyway...the solution you provide on route-node solves this in a better way

---

correction: now i see the point in partialMatching...you're absolutely right...sorry

**Comment by troch** [comment]
That is correct behaviour, it can be confusing. The question is in the reverse order: does `new Path('/')` partially match `/any/strange/long/route`?

I fixed an issue though around full matching with `var p = new Path('/?a')` and `p.match('/')` (https://github.com/troch/path-parser/commit/ada389705adae2464df6cb8838c4acd8f09fc177). That is not impacting the router as route-node will only use partialMatch and expect to be left with nothing to match for a successful match.

**Comment by troch** [comment]
@jamuhl with v2 of router5, a new plugin has been released called `router5-persistent-params` (https://github.com/router5/router5-persistent-param), which can help with having a set of query params on every route.

**Comment by jamuhl** [comment]
thank you for the update.

**Comment by troch** [comment]
v2 has a few breaking changes (nothing too major):
- https://github.com/router5/router5/blob/master/CHANGELOG.md#200-rc1-2016-01-18
- http://router5.github.io/docs/migration-2.html

**Pull request closed without merging**
